spring.data.neo4j.uri: bolt://localhost:7687
spring.data.neo4j.username: neo4j
spring.data.neo4j.password: secret
server.port: 8081

registration:
  enabled: false

jwt:
  secret: secret
  expiration-time: 86400000

traffic:
  scheduler:
    enabled: false
    cron: "0 0 0 * * *"
  client:
    api-key: 'secret-api-key'
